#server:
#  port: 8088
#  servlet:
#    context-path: /mock-server

spring:
  application:
    name: mock-server
  redis:
    database: 1
    host: 139.196.75.96
    port: 3333
    password: AdeTTT32312ttedsdcaHUHU

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://rm-uf6d76102edty93v6o.mysql.rds.aliyuncs.com/mock? serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&characterEncoding=utf8
#    username: ipay
#    password: 3pDhKnRQ5SqRC5MX
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: springHikariDataSource
#      minimum-idle: 5
#      maximum-pool-size: 15
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1765000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ipaylinks.test.mock.server.dao.model

#fuiou:
#  xml:
#    partnerId: FY000001
#    md5Key: e112dc63a91d420ba23c4e70ab33351f
#  json:
#    partnerId: FY000001
#    md5Key: e112dc63a91d420ba23c4e70ab33351f
#fuiou:
#  xml:
#    partnerId: FL000085
#    md5Key: sz6ZG0WgsIe2SyYPd6x2OhpsaaD4X4zE
#  json:
#    partnerId: FL000085
#    md5Key: sz6ZG0WgsIe2SyYPd6x2OhpsaaD4X4zE

#稠州银行测试环境公私钥
#czcb:
#  clientPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQClCOrjiNW3dLIhL+r+0yLawH7TgjBpXRggy+o8na184Q+MRo3mmItAan50ytX118dfhPc4zeKZ02LAHZQixQ+OfNdNepDOM5pcB0HfXXPaXSMW3xS0c500IeP2Pq6YkCOdEf0DiCdp3sByX5HoqR7yUHLHLy3cq3zr3AOxihp7EMmqeFLLWTswcJaWZ0G9Dj4scR4+mU7ISP+w76XAYra4tjWDO1rAIgLYtRlqYrinwL0K0YTeSCwT84cFvgTJWOg6/P3XU37doxms8DADPkBhXmYJI1XfuL/zJgcQVYXBeG+c9+MJvqkephYT1prddmweth9X34ePAoi3QT+Av3H1AgMBAAECggEAOlSGDMjS3MYqpW81zD5c3dtWmDQ2Hy9vtTvNfQIwDOjRIX/YbK3y3eAl9OqyJ/PNvHWXGaUvV7Yue3+Y2Zcz8eUvBevxnWgAwVExV5zEs2Pi4JUVUNhiMkheNa0e8b5UUBJJDoQDhjhcZbBgtk58KSIFB2CmAY49F3IKfig1RtRtN3GxO0fD+jvjJ+uPFi6uSYPdlfiIiHO/BJrNvuIk6LnKwmeCBjwhDfoOZj+LwIpS8xG8hwoksaMGycl3eT7MraGsXSq0NaUZzz0ycC8hJfE0saxrLeoQRja2FanvpRCQAbHvFrdick8zOl1AnxNta2uFEN3BqbZIaJQiC3bfCwKBgQDXKE8L04p+BfJz/alwtrfcyxp2/BgBRU06ItspUVIs+YsFa2jjfvLIud+Ov2mCzFWPoyXcrr1pF7h0xOsrB+C+fsm3j/xJbciXX2abX/4coiclb1H74T8OPU9vSNTMzcx8Hf2LqvpaVkci+GnB7KBkvY+o0+m87BJ0gNdpU02N8wKBgQDEXN+MWhjwNu7e94Owad4b1vY8WIZNv9qmSnjgnIiAvayqjRcv6YC1kv5c9aEkv3N4zron7PryVXu0FnsphTCA6FUBQB4VPpeJAIiP164L/BBChQn9DLaIW06YqMiu7YN00Q4mDK9UWcdbMs4+AD9R7ntztaVRKQI2t9BUj2MydwKBgGqa9k+NyRkYKUF/dez7G66yk7JQxjQa+mDL1HtsZ6MRIejVh2rxA6qhLju0a7r7M4mv9Jqbmg3wStzQlRUFGj5I4/mnxgE7/B/EjTp/HZFiZrMNrTl4KZ4Mksc49vdjIOZ+lZoWZWVNSoHxQ7VqYS6JHh0woqeQ8LP5AsKVG+AxAoGAI1WXAHmB/U/VQhgGAWu7hQT0gD1pxXndjYjfIYPpaEk5VeNXpc59066kyPOGUMeGrtl8VAznx02smeZluT33UWr9SOFRyH7f485NxJyJ/CwafO3Vs0xjWDwd84iDvD6PJiksQ5qKvkH9hqKozC1dN5ATdOnd2rHnbRM8kMrQjdcCgYBuxCktP8re2JDfXHp67TTZcqWjECLc96AHb2qv4Fa36Gs1f9JT7SzuAmaIzISzgy+oOsfeQ2ZkVu6be0wEgJAMJoh/I/jGoY6VcUkatIuZ7qXUTIZJ5D409KjI6Fc1RzC1eHjGZP3FsGzBp4loYUYC0UjWFg4EvDGo65vSXgertA==
#  serverPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApiv6uljjchFaMfP027BryqI1ZZvp+NsVu4zSkkdM4oMYATpKYMwbO/4bQXUC+1Z3g9XZ5Dod7QXl5z7bTNiEWvymBHigOXC0FGQTuc/EZpe4TnAxSUIcZa29fBQmlE3M8Os3CSSSdiLSbFoCl1IDBeknUL9cZoP36Xdx56B0B2Ofmb4Ey1iYQPYzuM3sEK72x3HbdEQEhTe4snfMngJ9pzlIy778gagGRMpadFaXGLluwxVAERDTd7dAPFD3VJ6NQWxGC5Es95tBU8WuyIqZUgTPD2Dy90DQQZLe+l344EHoWyEJAkUuI0I3qgeuxbDHQTa3r0ak15fC/sg21l/GFQIDAQAB
#  serverPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQClCOrjiNW3dLIhL+r+0yLawH7TgjBpXRggy+o8na184Q+MRo3mmItAan50ytX118dfhPc4zeKZ02LAHZQixQ+OfNdNepDOM5pcB0HfXXPaXSMW3xS0c500IeP2Pq6YkCOdEf0DiCdp3sByX5HoqR7yUHLHLy3cq3zr3AOxihp7EMmqeFLLWTswcJaWZ0G9Dj4scR4+mU7ISP+w76XAYra4tjWDO1rAIgLYtRlqYrinwL0K0YTeSCwT84cFvgTJWOg6/P3XU37doxms8DADPkBhXmYJI1XfuL/zJgcQVYXBeG+c9+MJvqkephYT1prddmweth9X34ePAoi3QT+Av3H1AgMBAAECggEAOlSGDMjS3MYqpW81zD5c3dtWmDQ2Hy9vtTvNfQIwDOjRIX/YbK3y3eAl9OqyJ/PNvHWXGaUvV7Yue3+Y2Zcz8eUvBevxnWgAwVExV5zEs2Pi4JUVUNhiMkheNa0e8b5UUBJJDoQDhjhcZbBgtk58KSIFB2CmAY49F3IKfig1RtRtN3GxO0fD+jvjJ+uPFi6uSYPdlfiIiHO/BJrNvuIk6LnKwmeCBjwhDfoOZj+LwIpS8xG8hwoksaMGycl3eT7MraGsXSq0NaUZzz0ycC8hJfE0saxrLeoQRja2FanvpRCQAbHvFrdick8zOl1AnxNta2uFEN3BqbZIaJQiC3bfCwKBgQDXKE8L04p+BfJz/alwtrfcyxp2/BgBRU06ItspUVIs+YsFa2jjfvLIud+Ov2mCzFWPoyXcrr1pF7h0xOsrB+C+fsm3j/xJbciXX2abX/4coiclb1H74T8OPU9vSNTMzcx8Hf2LqvpaVkci+GnB7KBkvY+o0+m87BJ0gNdpU02N8wKBgQDEXN+MWhjwNu7e94Owad4b1vY8WIZNv9qmSnjgnIiAvayqjRcv6YC1kv5c9aEkv3N4zron7PryVXu0FnsphTCA6FUBQB4VPpeJAIiP164L/BBChQn9DLaIW06YqMiu7YN00Q4mDK9UWcdbMs4+AD9R7ntztaVRKQI2t9BUj2MydwKBgGqa9k+NyRkYKUF/dez7G66yk7JQxjQa+mDL1HtsZ6MRIejVh2rxA6qhLju0a7r7M4mv9Jqbmg3wStzQlRUFGj5I4/mnxgE7/B/EjTp/HZFiZrMNrTl4KZ4Mksc49vdjIOZ+lZoWZWVNSoHxQ7VqYS6JHh0woqeQ8LP5AsKVG+AxAoGAI1WXAHmB/U/VQhgGAWu7hQT0gD1pxXndjYjfIYPpaEk5VeNXpc59066kyPOGUMeGrtl8VAznx02smeZluT33UWr9SOFRyH7f485NxJyJ/CwafO3Vs0xjWDwd84iDvD6PJiksQ5qKvkH9hqKozC1dN5ATdOnd2rHnbRM8kMrQjdcCgYBuxCktP8re2JDfXHp67TTZcqWjECLc96AHb2qv4Fa36Gs1f9JT7SzuAmaIzISzgy+oOsfeQ2ZkVu6be0wEgJAMJoh/I/jGoY6VcUkatIuZ7qXUTIZJ5D409KjI6Fc1RzC1eHjGZP3FsGzBp4loYUYC0UjWFg4EvDGo65vSXgertA==
#  clientPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApiv6uljjchFaMfP027BryqI1ZZvp+NsVu4zSkkdM4oMYATpKYMwbO/4bQXUC+1Z3g9XZ5Dod7QXl5z7bTNiEWvymBHigOXC0FGQTuc/EZpe4TnAxSUIcZa29fBQmlE3M8Os3CSSSdiLSbFoCl1IDBeknUL9cZoP36Xdx56B0B2Ofmb4Ey1iYQPYzuM3sEK72x3HbdEQEhTe4snfMngJ9pzlIy778gagGRMpadFaXGLluwxVAERDTd7dAPFD3VJ6NQWxGC5Es95tBU8WuyIqZUgTPD2Dy90DQQZLe+l344EHoWyEJAkUuI0I3qgeuxbDHQTa3r0ak15fC/sg21l/GFQIDAQAB

#稠州银行mock公私钥
#czcb:
#  clientPrivateKey: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQClEJN8MU4wqNort2mis+jU047UPZcTbv4ZzmrpenLqeCU2fuBhBsGWDHwMpz4DONIOdcH09ffYBjtf7QfBXwQe6sjKHl5vq2bdOqF/xOXCmJ2ViAMjo4kaPNdC2MEEaG2T1jZTGU6jp3J4BZCtD5qVe86wxBs34bNJra60G/WOo5GNWcXDstf3Es9o7OZ0rLWBVD7d3UPFpdbrRXTzY4GzfZ/lC/6gd/j/rxUgmSXuGCkX8orPn12W/MzIfUWbWmyeWbRpHVoKzntf+Coq5p3Z/6XJFiKoYBDKZDzDnHqHsSxj7iKKiJydLBOrrd0x2fZ0En908w6ZVwjGcDSvNZy1AgMBAAECggEBAJkoFUDR2vQJaE3R5CFEf5AiME+8ShaNERbO0aKLrF7kVdsHxJgilbLtKJjxAPgqW7VxDCOHqoz101fBbkW9LOym+uGXZhaFWm+BPGJ6RpnV07nwNsF1tvvyYeWzivzVDH907nkSbUYqU2sL9t6tMMjs1K5td7fVIu8FSanym1jZ7O9AcTZF51vgQcipOpYtmKgHuMzQVzA/TRubXWwG8LrSVIroQXiKkQe+9yPHoxE8vyZu/oDTNsQNJG6rkSnasj18TdbtQNwxMamfR94ZuJF/VrzpUnCyhMuHIniD4sni6Xf/QDxW6aWtiEmb3b4h8DDHLLWWJUU1pKrF6JIy9M0CgYEAz+TJ8H8l73098ioCK+nf6+FXTRt+UXxl7duauh6nJ3I2cx4Dna+qvbADjaxzne09ixbHl/0ceSpM5Qd9eKgGZWP2pdcUjpVQiAl2PyFufYzlP27nGJcBgC7M0qYknsbAoH7v0MKUZ/PrONzDalLjyxmiT/3K25l+xYao83sLM8sCgYEAy0KvUBJkpWm/QIUUP/pBoUQkql+3Jen17I9dKYdcREnpi43UVH4oTmssYL2ReUx13TpmmmX0t5eZW/XtFpjGGFySwgmjJtmQvFlUD9E7GuLmeVAIjhyDX8szmQPQ1Vwa9J3BL7zAMUHOjUHNrT/qwUPRHt77dg/IqUuhiWc1YX8CgYEAhA6S8D/0OwLVfKSOqJJxeQa1S/ew79YTcVpUGPIrv/Te/ZUNOvdBgCj0uOPYtXLj6xxXQQa5NYZXPgzZ+PDSz0kGfiX3mvLiKufHwyZbZ0k+vmKWTZpui5wu44hCLtGVvt2jPHq9hqL8wiwJvdpVdMgdwK44U/JXAuYdID0Cyq0CgYEAmUr3kLnucdnoxS4YcY+5g3gy9tMs+0kRkZElv7Y4XcAohHk4k2h52Xp2g5c0aXjCw0/SJcuS3gtVO8ejQRGDBMh8Xh6KjzgyMfpkrXEs1EAfdYpoiVTzt4E2rsXz75WBNs7q7ae6guuQbXQdO/YihBMzWcbtesK4oQVLFKdj2N0CgYEAoB3fYqQsZiVkMsxGjo3uyXlb3vvbSC8nu9VC/qYdg4DB5Uew5rsPQpsWRs4mJ4o76O00omg76fXt35EI87r2eIffVutA73yQ8DvtEy4TKhRR+fPV3gG03H0aO7PRY3Sda7RrlsyHNfnuiswhrm1Gtr+l0hbJXmVMomcN9NgYJCI=
#  serverPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Rr5J6loDpwOQJhI/4hVTOk+JZdvFwG913keXOW0kmxeh/wUlUG++RqAHjMQqdV/CV32XPsh8N6XnPTK/wBvB4sCgcThNnpLcXN24Tbmx/svnCk+KRwCD5MJBx5PEMro7bTLlEKQZWwKb/cnu1L8KUeL4dNCpj6/lwfxcNaJytqfuItCYJukXC92bJ8eRWoX2efFCE0ICNCWAvgsfhgsbl6dlKQE8EXtBA7v+RHcWtr9kB8avZORSKTEpF/qqDd9vt0K6cKgVLXnX/COqHv0SwM72BK+LoJ3rEP8BXVj8FLhOIVf0C4UVVqkwejiRpZ8F+HCWq/ckcs+h67iKcwopwIDAQAB
#  serverPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZGvknqWgOnA5AmEj/iFVM6T4ll28XAb3XeR5c5bSSbF6H/BSVQb75GoAeMxCp1X8JXfZc+yHw3pec9Mr/AG8HiwKBxOE2ektxc3bhNubH+y+cKT4pHAIPkwkHHk8QyujttMuUQpBlbApv9ye7UvwpR4vh00KmPr+XB/Fw1onK2p+4i0Jgm6RcL3Zsnx5FahfZ58UITQgI0JYC+Cx+GCxuXp2UpATwRe0EDu/5Edxa2v2QHxq9k5FIpMSkX+qoN32+3QrpwqBUtedf8I6oe/RLAzvYEr4ugnesQ/wFdWPwUuE4hV/QLhRVWqTB6OJGlnwX4cJar9yRyz6HruIpzCinAgMBAAECggEANVWvB9NSQOSNi8jdhgkUC4TxQ4LkQ56l6J1UnDXCGoaM4pNG6zPvmnqsJr8cxNwyDTcMIuN+/xFv5Zstk1+j5xJ7Vy3qtdttVT2sYr9+Cnrmw1JOdwLubq0Mdrc3bUSr3Fmh+ZYwqvnTxpXNKPPGBs4QyzV/FiAsKQpGghXyW+bNSIyzbrZ9vyx58SjLCIqiVgX9rd7r05sDMfbtWhaZm6PhEqmgwioLa+muF5QJ12HZPo6vzS3jXRIOYisyq3wZyknIAifl1NKd7LY/jNTlEFJVfs9Mj+2+sWWsaMdP1Uq+uYL95Qw8njdesaTmPG4WFSSYDslvKJ6PoSt4vICegQKBgQD/i7JYPK1uHdkBOT59TfFDol+ES8K2UH88Z/3j6Ij2+tvw0blfJKd5nBRcct8wPz2DtimAs+tmX/O/rL6YSrZaTsIGT7SVoKEgPa+0Q/eJqU2gnTbLpsNlRpmyimhwxIM7qMkM0DpFm51W7PtR0/G72wIS8Cljo+iVmcp80Ck7FwKBgQDZfcgfs/WlZOi5zUCBpy3cB5IdsZdUq0w3oElaL5r65rwIb43spuAwyIKGyKDvuf2BeizVsvCaKo+jBBIz66zwtXBmS9NF+DE6ZGWsvZ4EqFVpF80zm54FPrwRJ0phUi+fY1BWLecwD9uAMFTLASvuCzilYHPOUJGwoSNlSXW48QKBgE2vVxkx4Psvwa94ioGnNyf7bZQXP+sSj4t6hZlKMJD8c+5Co1rEFtGGXD46gZT2NKocr4M7rt0hYEUtq4c6dzL+7Ebk5h3yhej6N7bSTqcfu8SO5oCEgrQAAWtgXh2h788sIWpuxrgwdWVeh4w5pSwZiQjez4ZF5sfLx92nnlEjAoGAdTg/tiaODNh4PjwLulVaeC50aCChSXcRmyF+p2blBrl5Oqq1OYkvZ9uJzg8v/kSmBzTMGVlaKB0sUVYOYYFyMkH4FIplkl6UWb5mtlV0Z1o6vmufo2MKJhWL00rz4cQj+qnSUMBozBSf31UtPkShYqkVnLyBbf8qpqISq7KOCmECgYEA2ICIbL3ApgPS0ZRE16MD9nlVRc6DWGGDwPyA6XJTWf616vAP1Hc239kAIZubFH8y4KHIj46NZ+a96q4rhemhvf9XTs+yUXG5nRnCtZVhXOfJIvt/1q0AuL3TT/ezJFYt0+tKHpQEMVzPVRV66BTLxW8TTun+xCqvZNaJUvWKdVQ=
#  clientPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApRCTfDFOMKjaK7dporPo1NOO1D2XE27+Gc5q6Xpy6nglNn7gYQbBlgx8DKc+AzjSDnXB9PX32AY7X+0HwV8EHurIyh5eb6tm3Tqhf8TlwpidlYgDI6OJGjzXQtjBBGhtk9Y2UxlOo6dyeAWQrQ+alXvOsMQbN+GzSa2utBv1jqORjVnFw7LX9xLPaOzmdKy1gVQ+3d1DxaXW60V082OBs32f5Qv+oHf4/68VIJkl7hgpF/KKz59dlvzMyH1Fm1psnlm0aR1aCs57X/gqKuad2f+lyRYiqGAQymQ8w5x6h7EsY+4iioicnSwTq63dMdn2dBJ/dPMOmVcIxnA0rzWctQIDAQAB

#上海银行测试环境公私钥
bosc:
  clientPrivateKeyPath: /opt/cfp/bosc/private.pfx
  clientPrivateKeyPassword: 123123
  serverPublicKeyPath: /opt/cfp/bosc/public.cer

#上海银行mock公私钥
#bosc:
#  clientPrivateKeyPath: /opt/mock/bosc/privateKey.p12
#  clientPrivateKeyPassword: password
#  serverPublicKeyPath: /opt/mock/bosc/publicKey.cer
#  serverPrivateKeyPath: /opt/mock/bosc/privateKey.p12
#  serverPrivateKeyPassword: password
#  clientPublicKeyPath: /opt/mock/bosc/publicKey.cer

#DBS星展银行
dbs:
#  serverPublicKey:
#  clientPrivateKey:
  clientPrivateKeyPassword: qiyun@ipay888
  orgId: CNSHA006
  quoteUrl: https://api-ideal-uat.dbs.com/rapid/forex/v1/rfq/rates
  quoteKeyId: 43650002-9157-4c9e-9eeb-9a8362acc5c8
  bookingUrl: https://api-ideal-uat.dbs.com/rapid/forex/v1/rfq/booking
  bookingKeyId: 43650002-9157-4c9e-9eeb-9a8362acc5c8
  actUrl: https://api-ideal-uat.dbs.com/rapid/stpcn/v1/payment/initiatePayment
  actKeyId: 0f8b8c57-9ab0-48a9-8f48-ff1db9be55de
  ttUrl: https://api-ideal-uat.dbs.com/rapid/stpcn/v1/payment/initiatePayment
  ttKeyId: 0f8b8c57-9ab0-48a9-8f48-ff1db9be55de
  accountBalanceEnquiryUrl: https://api-ideal-uat.dbs.com/rapid/enquiry/v1/account/balance
  accountBalanceEnquiryKeyId: 4e151320-6665-49b8-aa40-b89b4c4a0389
  transactionEnquiryUrl: https://api-ideal-uat.dbs.com/rapid/enquiry/v1/transaction/status
  transactionEnquiryKeyId: de8b9aef-f6f3-4dee-8383-1cb5e92c6c2a